/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twitter;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.logging.Level;
import java.util.logging.Logger;
import twitter4j.DirectMessage;
import twitter4j.ResponseList;
import twitter4j.Twitter;
import twitter4j.TwitterException;
import twitter4j.api.DirectMessagesResources;

/**
 *
 * @author agam sharma
 */
public class DirectMessageUserFrame extends javax.swing.JFrame {

    ArrayList<DirectMessage> list;
    Twitter twitter;
    long id;

    public DirectMessageUserFrame(Twitter twitter, long id) {
        initComponents();
        this.twitter = twitter;
        this.id = id;
        Thread t=new Thread(new fetchmsg());
        t.start();
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(700,500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbname = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        btse = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        btre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(lbname);
        lbname.setBounds(250, 10, 180, 20);

        jScrollPane1.setViewportView(jEditorPane1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(90, 70, 530, 280);

        btse.setText("SEND");
        btse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btseActionPerformed(evt);
            }
        });
        getContentPane().add(btse);
        btse.setBounds(483, 390, 90, 40);

        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane2.setViewportView(ta);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(90, 380, 370, 70);

        btre.setText("REFRESH");
        btre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btreActionPerformed(evt);
            }
        });
        getContentPane().add(btre);
        btre.setBounds(630, 20, 77, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btreActionPerformed
        Thread t1=new Thread(new fetchmsg());
        t1.start();
    }//GEN-LAST:event_btreActionPerformed

    private void btseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btseActionPerformed
       String msg=ta.getText();
       if(!msg.equals(""))
       {
           try {
               twitter.sendDirectMessage(id, msg);
               Thread t2=new Thread(new fetchmsg());
               t2.start();
           } catch (TwitterException ex) {
               Logger.getLogger(DirectMessageUserFrame.class.getName()).log(Level.SEVERE, null, ex);
           }
           ta.setText("");
           
       }
    }//GEN-LAST:event_btseActionPerformed

    class fetchmsg implements Runnable {

        @Override
        public void run() {
            try {
                list = new ArrayList<>();
                DirectMessagesResources dmr = twitter.directMessages();
                ResponseList<DirectMessage> reclist = dmr.getDirectMessages();
                for (DirectMessage d : reclist) {
                    if (d.getSenderId() == id) {
                        list.add(d);
                    }
                }
                ResponseList<DirectMessage> sentlist = dmr.getSentDirectMessages();
                for (DirectMessage d : sentlist) {
                    if (d.getRecipientId() == id) {
                        list.add(d);
                    }
                }
                Collections.sort(list, new Comparator<DirectMessage>() {
                    @Override
                    public int compare(DirectMessage o1, DirectMessage o2) {
                        return o2.getCreatedAt().compareTo(o1.getCreatedAt());
                    }
                }
                );
                System.out.println(list.size());
                String s="'";
                for(DirectMessage d:list)
                {
                    if(d.getSenderId()==twitter.getId())
                    {
                        s+="<h2 align=\"left\"style=\"color:blue\">"+d.getText()+"</h2>";
                    }
                    else
                    {
                         s+="<h2 align=\"right\"style=\"color:red\">"+d.getText()+"</h2>";
                    }
                }
                jEditorPane1.setContentType("text/html");
                jEditorPane1.setText(s);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DirectMessageUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DirectMessageUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DirectMessageUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DirectMessageUserFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //   new DirectMessageUserFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btre;
    public javax.swing.JButton btse;
    public javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbname;
    public javax.swing.JTextArea ta;
    // End of variables declaration//GEN-END:variables
}
