/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twitter;

/**
 *
 * @author agam sharma
 */
public class DMPanel extends javax.swing.JPanel {

    /**
     * Creates new form DMPanel
     */
    public DMPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pa1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(null);

        pa1.setBackground(new java.awt.Color(153, 153, 153));
        pa1.setLayout(null);
        jScrollPane1.setViewportView(pa1);

        add(jScrollPane1);
        jScrollPane1.setBounds(70, 50, 520, 340);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel pa1;
    // End of variables declaration//GEN-END:variables
}
