/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twitter;

/**
 *
 * @author agam sharma
 */
public class HomeTweetPanel extends javax.swing.JPanel {

    /**
     * Creates new form HomeTweetPanel
     */
    public HomeTweetPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jpa = new javax.swing.JPanel();

        setLayout(null);

        jpa.setLayout(null);
        jScrollPane1.setViewportView(jpa);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 720, 490);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel jpa;
    // End of variables declaration//GEN-END:variables
}
