/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twitter;

import javax.swing.JTextArea;

/**
 *
 * @author agam sharma
 */
public class ScheduleTweetPanel extends javax.swing.JPanel {

    /**
     * Creates new form ScheduleTweetPanel
     */
    public ScheduleTweetPanel() {
        initComponents();
        for(int i=0;i<=23;i++)
        {
            cbhr.addItem(i+"");
            
        }
       for(int i=0;i<=60;i++)
       {
           cbmin.addItem(i+"");
       }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbpr = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btsch = new javax.swing.JButton();
        cbhr = new javax.swing.JComboBox<>();
        cbmin = new javax.swing.JComboBox<>();

        setLayout(null);

        lbpr.setText("profilepic");
        add(lbpr);
        lbpr.setBounds(62, 47, 106, 96);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(216, 47, 330, 130);

        btsch.setText("SCHEDULE");
        add(btsch);
        btsch.setBounds(300, 230, 120, 40);

        add(cbhr);
        cbhr.setBounds(470, 220, 28, 20);

        add(cbmin);
        cbmin.setBounds(540, 220, 28, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btsch;
    public javax.swing.JComboBox<String> cbhr;
    public javax.swing.JComboBox<String> cbmin;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    public javax.swing.JLabel lbpr;
    // End of variables declaration//GEN-END:variables
}
