/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twitter;

/**
 *
 * @author agam sharma
 */
public class SingleDMPanel extends javax.swing.JPanel {

    /**
     * Creates new form SingleDMPanel
     */
    public SingleDMPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbpr = new javax.swing.JLabel();
        lb1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 255));
        setLayout(null);
        add(lbpr);
        lbpr.setBounds(20, 20, 70, 60);
        add(lb1);
        lb1.setBounds(134, 40, 150, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lb1;
    public javax.swing.JLabel lbpr;
    // End of variables declaration//GEN-END:variables
}
