/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twitter;

import java.awt.Color;

/**
 *
 * @author agam sharma
 */
public class SingleUseTweet extends javax.swing.JPanel {

    /**
     * Creates new form SingleUseTweet
     */
    public SingleUseTweet() {
        initComponents();
        setBackground(Color.BLUE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lb1 = new javax.swing.JLabel();
        lb2 = new javax.swing.JLabel();
        lbtw = new javax.swing.JLabel();
        btfav = new javax.swing.JButton();

        setBackground(new java.awt.Color(51, 153, 255));
        setLayout(null);

        lb1.setText("pic");
        add(lb1);
        lb1.setBounds(10, 0, 80, 60);

        lb2.setBackground(new java.awt.Color(255, 255, 255));
        lb2.setText("@");
        add(lb2);
        lb2.setBounds(110, 20, 170, 30);

        lbfav.setText("fav");
        add(lbfav);
        lbfav.setBounds(110, 70, 50, 14);

        lbtw.setText("retweet");
        add(lbtw);
        lbtw.setBounds(190, 70, 50, 14);

        btfav.setText("fav/unfav");
        add(btfav);
        btfav.setBounds(270, 70, 81, 23);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btfav;
    public javax.swing.JLabel lb1;
    public javax.swing.JLabel lb2;
    public final javax.swing.JLabel lbfav = new javax.swing.JLabel();
    public javax.swing.JLabel lbtw;
    // End of variables declaration//GEN-END:variables
}
