/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package twitter;

/**
 *
 * @author agam sharma
 */
public class SingleUserProfile extends javax.swing.JPanel {

    /** Creates new form SingleUserProfile */
    public SingleUserProfile() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbpic = new javax.swing.JLabel();
        lbname = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(null);

        lbpic.setText("jLabel1");
        lbpic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbpic);
        lbpic.setBounds(10, 10, 130, 80);

        lbname.setText("jLabel1");
        add(lbname);
        lbname.setBounds(160, 20, 110, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel lbname;
    public javax.swing.JLabel lbpic;
    // End of variables declaration//GEN-END:variables

}
