/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package twitter;

import java.awt.Color;

/**
 *
 * @author agam sharma
 */
public class SingleSerchPanel extends javax.swing.JPanel {

    /**
     * Creates new form SingleSerchPanel
     */
    public SingleSerchPanel() {
        initComponents();
        pasc.setBackground(Color.darkGray);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfsc = new javax.swing.JTextField();
        btsc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        pasc = new javax.swing.JPanel();
        btsc2 = new javax.swing.JButton();
        btdm = new javax.swing.JButton();

        setLayout(null);

        tfsc.setText("@");
        add(tfsc);
        tfsc.setBounds(110, 40, 370, 30);

        btsc.setText("SEARCH");
        add(btsc);
        btsc.setBounds(540, 40, 73, 23);

        pasc.setLayout(null);
        jScrollPane1.setViewportView(pasc);

        add(jScrollPane1);
        jScrollPane1.setBounds(100, 90, 390, 370);

        btsc2.setText("follo/unfollo");
        add(btsc2);
        btsc2.setBounds(540, 90, 89, 23);

        btdm.setText("DM");
        add(btdm);
        btdm.setBounds(403, 70, 70, 20);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btdm;
    public javax.swing.JButton btsc;
    public javax.swing.JButton btsc2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel pasc;
    public javax.swing.JTextField tfsc;
    // End of variables declaration//GEN-END:variables
}
